variables:
  ENV: "development"
  LC_ALL: "C"


default:
  image: python:3.13
  cache:
    paths:
      - .pip-cache/
  before_script:
    - python --version
    - pip install --upgrade pip
    - pip install .[dev]
    - git submodule update --init --recursive

stages:
  - test

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - pytest

lint-test-job:
  stage: test
  script:
    - echo "Linting code... This will take about 10 seconds."
    - mypy
    - black . --check
    - echo "No lint issues found."