# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
    -   id: autoflake
  - repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
    -   id: flake8
  - repo: https://github.com/johann-petrak/licenseheaders
    rev: 'v0.8.8'
    hooks:
        - id: licenseheaders
          types: ['python']
          args: [
            "-x",
            "./arretify/_vendor/",
            "-E",
            ".py",
            "-t",
            "./scripts/apache-2.tmpl",
            "-o",
            "Direction générale de la prévention des risques (DGPR)",
            "-y",
            "2025",
            "-n",
            "Arrêtify",
            "-u",
            "https://github.com/mte-dgpr/arretify",
            "-f"
          ]